### ISSUE TITLE
Suck on waiting for port 9906

### ISSUE THREAD

**Issue by inzel** [ahebrank/dumpviewer#4]
I came across your tool for a project Im working on with sql databases. Its a wonderful idea but no matter what I try I always end up stuck on waiting for port 9906. Anything I can provide to assist with determining why?

Thank you in advance

**Comment by inzel** [comment]
BTW... the port is open and in listening status. Maybe its just hung up on installing something?

**Comment by inzel** [comment]
New update... this appears to be an issue with Kali because it works fine on a mac

**Comment by ahebrank** [comment]
Now using docker healthcheck, so this shouldn't by an issue anymore.
