### ISSUE TITLE
URL in view script does not work with PHP MyAdmin 5.1.1

### ISSUE THREAD

**Issue by robotdan** [ahebrank/dumpviewer#5]
The hard coded URL in https://github.com/ahebrank/dumpviewer/blob/97f3211ca5f9270a429df4994104bd63924bec74/view#L13 did not work for me. 

Current value :

```
open "http://localhost:9980/db_structure.php?server=1&db=dump"
```

My guess is that this will depend upon the version of PHP admin installed by Docker. I'm on version `5.1.1` of `phpmyadmin` ( `phpmyadmin/phpmyadmin:5.1.1`).

So with this version of PHP My Admin, the correct open command would be:

```
open "http://localhost:9980/index.php?route=/database/structure&server=1&db=dump"
```

**Comment by ahebrank** [comment]
I think this is working now with recent changes.
